#include "DDSX.h"

namespace dds {
	EFormat DDSLoadingDesc::convert_fmts[][2] =
	{
		{ EF_BC1, EF_ARGB8 },
		{ EF_BC1_SRGB, EF_ARGB8_SRGB },
		{ EF_BC2, EF_ARGB8 },
		{ EF_BC2_SRGB, EF_ARGB8_SRGB },
		{ EF_BC3, EF_ARGB8 },
		{ EF_BC3_SRGB, EF_ARGB8_SRGB },
		//{ EF_BC4, EF_R8 },
		//{ EF_BC4_SRGB, EF_R8 },
		{ EF_SIGNED_BC4, EF_SIGNED_R8 },
		//{ EF_BC5, EF_GR8 },
		//{ EF_BC5_SRGB, EF_GR8 },
		{ EF_SIGNED_BC5, EF_SIGNED_GR8 },
		{ EF_BC6, EF_ABGR16F },
		{ EF_SIGNED_BC6, EF_ABGR16F },
		{ EF_BC7, EF_ARGB8 },
		{ EF_BC7_SRGB, EF_ARGB8 },
		{ EF_ETC1, EF_ARGB8 },
		{ EF_ETC2_BGR8, EF_ARGB8 },
		{ EF_ETC2_BGR8_SRGB, EF_ARGB8_SRGB },
		{ EF_ETC2_A1BGR8, EF_ARGB8 },
		{ EF_ETC2_A1BGR8_SRGB, EF_ARGB8_SRGB },
		{ EF_ETC2_ABGR8, EF_ARGB8 },
		{ EF_ETC2_ABGR8_SRGB, EF_ARGB8_SRGB },
		{ EF_R8, EF_ARGB8 },
		{ EF_SIGNED_R8, EF_SIGNED_ABGR8 },
		{ EF_GR8, EF_ARGB8 },
		{ EF_SIGNED_GR8, EF_SIGNED_ABGR8 },
		{ EF_ARGB8_SRGB, EF_ARGB8 },
		{ EF_ARGB8, EF_ABGR8 },
		{ EF_R16, EF_R16F },
		{ EF_R16F, EF_R8 },
	};
}